function init(self)
	msg.post(".", "acquire_input_focus")

	local res = vmath.vector4(800, 600, 0.5, 0)
	sprite.set_constant("/back#sprite", "resolution", res)
end

function final(self)
	msg.post(".", "release_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("mouse_left") and action.pressed then
		sound.play("/back#sound_next")
		msg.post("main:/loader#script", "start_game")
	end
end
